steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/my-web-pf/github.com/ivanbaug/portfolio-flask:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/my-web-pf/github.com/ivanbaug/portfolio-flask:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'portfolio-flask', '--region=us-east1', '--platform=managed','--image=gcr.io/my-web-pf/github.com/ivanbaug/portfolio-flask:$COMMIT_SHA', '--max-instances=2']

